### ISSUE TITLE
Programar te deixará rico?

### ISSUE THREAD

**Issue by gabcostasilva** [MarioDeAraujoCarvalho/hello-world-git#10]

**Comment by froeder** [comment]
NÃO

**Comment by gabcostasilva** [comment]
=,(

**Comment by froeder** [comment]
Achou q ia ganhar dineiro programando? Achou errado

**Comment by MateusGabi** [comment]
Não sonhe

**Comment by MateusGabi** [comment]
![image](https://user-images.githubusercontent.com/14940643/46541947-46490500-c88b-11e8-90eb-f5b8516c04b9.png)
